# Generated by Django 4.1.3 on 2025-02-23 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='api.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=250)),
                ('tipo_video', models.CharField(choices=[('Sinal', 'Sinal'), ('Soletrando', 'Termo em Libras Soletrando'), ('Significado', 'Significado')], max_length=20)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.termo')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='api.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='dominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='api.dominio'),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='api.categoria')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='api.termo')),
            ],
            options={
                'unique_together': {('termo', 'categoria')},
            },
        ),
    ]
