# Generated by Django 4.1.3 on 2025-03-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='videos/default.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
